blank_issues_enabled: true
contact_links:
  - name: Security vulnerabilities
    url: https://devtools-for-livewire.com
    about: If you want to report a security issue, please contact our support - support@devtools-for-livewire.com
