name: Feature Request
description: Request a new feature.
title: "[FEATURE] "
body:
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should happen?
      description: A clear and concise description of what you expect to happen.
      placeholder: "It should..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the request here.
      placeholder: "Maybe you should know that..."
